[workspace]
authors = ["wc-caldwell <clay.caldwell124@gmail.com>"]
channels = ["conda-forge"]
name = "WaterDig-AutoBAG"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"

[feature.process.dependencies]
numpy = ">=2.4.2,<3"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.17.1,<2"
gdal = ">=3.12.2,<4"
pyproj = ">=3.7.2,<4"
pandas = ">=3.0.1,<4"
geopandas = ">=1.1.2,<2"
fiona = ">=1.10.1,<2"
verde = ">=1.8.1,<2"
pygeohydro = ">=0.19.4,<0.20"

[feature.process.pypi-dependencies]

[feature.eval.dependencies]
python = "3.10.*"

[feature.eval.pypi-dependencies]

[environments]
process = ["process"]                   
eval    = ["eval"] 
